version: 2

sources:
  - name: snowflake_sample_data
    description: 'sample database provided by snowflake_sample_data'
    database: snowflake_sample_data
    schema: TPCDS_SF10TCL
    tables:
      - name: store_sales
        description: 'Sales Details'
